# -*- coding: utf-8 -*-
"""python_B1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtgw2PQEw7xx-enRcdUee_lIlmZQXVbW
"""

print(5 / 8)

print(7+10)

# Đây là một chú thích
print("Hello Python") # in ra dòng Hello Python

# Phép cộng, phép trừ
print(5 + 5)
print(5 - 5)

# Phép nhân, phép chia
print(3 * 5)
print(10 / 2)

# Tính lũy thừa
print(4 ** 2)

# Chia lấy phần dư
print(18 % 7)

# Số tiền An nhận được sau 15 năm gửi ngân hàng
print(1000 * 1.1**15)

x = 5

print(x)

# Khởi tạo biến savings có giá trị bằng 1000
x = 1000

# In ra giá trị của biến savings
print(x)

# Khởi tạo biến savings
savings = 1000


# Khởi tạo biến factor biểu diễn lãi suất ngân hàng
factor   = 1.1

# Tính toán số tiền và gán giá trị vào biến result
result = savings * factor ** 15

# In ra giá trị của result
print (result)

# Tạo biến desc
desc = 'Data Science'

# Tạo biến profitable
profitable = True

# Khai báo biến a
a = 10
# In ra kiểu dữ liệu của a
print(type(a))

# In ra kiểu dữ liệu của biến savings
print(type(savings))

# In ra kiểu dữ liệu của biến factor
print(type(factor))

# In ra kiểu dữ liệu của biến desc
print(type(desc))

# In ra kiểu dữ liệu của biến profitable
print(type(profitable))

# Các biến đã được khai báo sẵn cho bạn
savings = 1000
factor = 1.10
desc = "Data Science"

# Tính tích của savings và factor, lưu kết quả vào year1
year1 = savings * factor

# In ra kiểu dữ liệu của year1
print(type(year1))

# Tính tổng của desc và desc rồi lưu kết quả vào doubledesc
doubledesc = desc * 2

# In ra doubledesc
print(doubledesc)

# Khai báo biến savings và result
savings = 1000
result = 1000 * 1.10 ** 15

# Sửa lại lệnh in dưới đây cho đúng
print("Tôi gửi ngân hàng $" + str(savings) + ", sau 15 năm, bây giờ tôi đã có $" + str(result) + ". Tuyệt vời!")

# Khai báo pi_string
pi_string = "3.1415926"

# Chuyển pi_string sang float: pi_float
pi_float = float(pi_string)