# -*- coding: utf-8 -*-
"""python_B2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-HkqrxcpX3N9m6Nbo9F0EZT19zX-XPU
"""

hall = 11.5
kit = 18.0
liv = 19.75
bet = 10.75
bath = 9.5
areas = [hall, kit, liv, bet, bath]
print(areas)

hall = 11.5
kit = 18.0
liv = 19.75
bet = 10.75
bath = 9.5
areas = [hall, kit, "living room", liv, bet, "bath room", bath]
print(areas)

hall = 11.5
kit = 18.0
liv = 19.75
bet = 10.75
bath = 9.5
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bet],
         ["bathroom", bath]]
print(house)
print(type(house))

areas = ["hallway",11.5,"kitchen",18.0,"living room",19.75,"bedroom",10.75,"bathroom",9.5]
print(areas [1])
print(areas [-1])
print(areas [3])

areas = ["hallway",11.5,"kitchen",18.0,"living room",19.75,"bedroom",10.75,"bathroom",9.5]
eat_sleep_area = areas[1] + areas[-1] * areas[-3]
print(eat_sleep_area)

areas = ["hallway",11.5,"kitchen",18.0,"living room",19.75,"bedroom",10.75,"bathroom",9.5]
downstairs = areas[0:6]
upstairs = areas[6:-1]
print(downstairs)
print(upstairs)

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

downstairs = areas[:6]
upstairs = areas[6:]

print(downstairs)
print(upstairs)

x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
x[2][2]
x[2][:2]

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

areas[-1] = 10.50

areas[4] = 'chill zone'

print(areas)

areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

areas_1 = areas  + ["poolhouse", 24.5]

areas_2 = list(areas_1)
areas_2.extend(["garage", 15.45])

print(areas_1)
print(areas_2)

areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

del(areas[-4])

del(areas[-3])

print(areas)

areas = [11.25, 18.0, 20.0, 10.75, 9.50]

areas_copy = list(areas)

areas_copy[0] = 5.0

print(areas)

var1 = [1,2,3,4]
var2 = True
print(type(var1))
print(len(var1))
out2 = int(var2)

help (complex)

help(sorted)

first = [11.25,18.0,20.0]
second = [10.75,9.50]
full = first + second
full_sorted = sorted(full, reverse=True)

print(full_sorted)